name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_APK:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
    
      - name: Build Debug APK
        run: './gradlew assembleDebug'
        
  UnitTest:
    needs: [Build_APK]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
        
  Upload_Firebase:
    needs: [UnitTest]
    runs-on: ubuntu-latest
    steps:
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_APP_TOKEN}}
          groups: test
          file: app/build/outputs/apk/debug/app-debug.apk
        
  Upload_Slack:
    needs: [UnitTest]
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL : ${{secrets.SLACK_WEBHOOK_URL}}  

    steps:
      - name: Upload APK
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: '#apk배포'
          file_path: 'app/build/outputs/apk/debug/app-debug.apk'
          file_name: 'app-debug.apk'
          file_type: 'apk'
          initial_comment: '테스트 앱 배포'
      - name: Slack Notification
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          steps: ${{ toJson(steps) }}
          author_name: Github Action Test
          fields: repo,message,commit,author
          channel: '#테스트'
        if: always()
