name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK_URL : ${{secrets.SLACK_WEBHOOK_URL}}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Test Build APK
      run: bash ./gradlew assembleRelease --stacktrace
      
    - run: './gradlew assembleRelease'
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
        file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
        file_name: 'app-release-unsigned.apk'
        file_type: 'apk'
        initial_comment: '${{ github.ref }} 테스트 앱 슬랙 배포 성공'  
        
    - name: 테스트용 apk artifact 업로드
      uses: actions/upload-artifact@v2
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Slack Notification
      uses: 8398a7/action-slack@v3.15.0
      with:
        status: ${{job.status}}
        steps: ${{ toJson(steps) }}
        author_name: Github Action Test
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        channel: '#테스트'
      if: always()
    
