name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK_URL : ${{secrets.SLACK_WEBHOOK_URL}}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Test Build APK
      run: bash ./gradlew assembleRelease --stacktrace
    

    - name: Slack Notification
      uses: 8398a7/action-slack@v3.15.0
      with:
        status: ${{job.status}}
        steps: ${{ toJson(steps) }}
        author_name: Github Action Test
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        channel: '#테스트'
      if: always()
      
    - name: slack upload file
      uses: MeilCli/slack-upload-file@v3.0.0
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        file_path: 'message.txt'
        file_name: 'message.txt'
        file_type: 'text'
        initial_comment: 'APK File Upload'
